# RULES
RULE_OK = 0
RULE_FAIL = 1

# COMMIT STATUS CHANGE
COMMIT_STATUS_DRY_RUN = 2
COMMIT_STATUS_OK = 3
COMMIT_STATUS_ERROR = 4
COMMIT_STATUS_SKIPPED = 5

# RESULT FOR COMMIT
RESULT_SKIPPED = 6
RESULT_SUCCESS = 7
RESULT_FAILURE = 8
RESULT_ERROR = 9
